name: Deploy to Vercel

on:
  push:
    branches:
      - main # change this to your default branch
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Run unit tests
        run: yarn test:unit
      - name: Run end-to-end tests
        run: yarn test:e2e
      - name: Install Vercel CLI
        run: yarn add -g vercel@latest
      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
