name: Run Tests

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn ci
      - name: Install Playwright Browser
        run: npx playwright install --with-deps
      - name: Updrade playwright
        run: yarn upgrade playwright
      - name: Run unit tests
        run: yarn test:unit
      - name: Run end-to-end tests
        run: yarn test:e2e
